import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { client } from "@ntq/sdk";
import { MushafOptionsProvider } from "@/contexts/mushafOptionsContext";
import { SelectedProvider } from "@/contexts/selectedsContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Natiq Quran",
    description: "Generated by create next app",
};

client.setConfig({
    baseURL: process.env.API_URL || "https://api.natiq.net",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <MushafOptionsProvider>
                        <SelectedProvider>{children}</SelectedProvider>
                    </MushafOptionsProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
